[tool.pytest.ini_options]
markers = [
    "mark4: tests for level 4",
    "mark6: tests for level 6",
    "mark8: tests for level 8",
    "mark10: tests for level 10",
    "stage_2_1_crawler_config_check: tests for Crawler config validation",
    "stage_2_2_crawler_check: tests for Crawler",
    "stage_2_3_HTML_parser_check: tests for HTML Parser",
    "stage_2_4_dataset_volume_check: tests for Dataset volume validation",
    "stage_2_5_dataset_validation: tests for Dataset structure validation",
    "stage_3_1_dataset_sanity_checks: tests for Dataset sanity checks",
    "stage_3_2_corpus_manager_checks: tests for Corpus Manager",
    "stage_3_3_conllu_token_checks: tests for Conllu Token",
    "stage_3_4_admin_data_processing: tests for Admin data processing",
    "stage_3_5_student_dataset_validation: tests for Student dataset validation",
    "stage_3_6_advanced_morphological_processing: tests for advances processing pipeline",
    "stage_4_pos_frequency_pipeline_checks: tests for POSFrequencyPipeline",
    "lab_5_scrapper: all checks for the scrapper",
    "lab_6_pipeline: all checks for the pipeline",
    "core_utils: all checks for the core utils"
]
norecursedirs = [
    "venv*"
]

[tool.coverage.run]
omit = [
    '*/tests/*',
    '*/ud_validator/*',
    'lab_5_scrapper/scrapper_dynamic.py',
]

[tool.mypy]
python_version = "3.10"
exclude = [
    'venv*',
    'tests/',
    'tools/'
]

disallow_untyped_defs = true
disallow_any_unimported = false
no_implicit_optional = true
check_untyped_defs = true
warn_return_any = true
show_error_codes = true
warn_unused_ignores = false

# simplifications
disable_error_code = [
    'var-annotated',
    'union-attr',

    # needed for seminars, to this moment not fixed: https://github.com/python/mypy/issues/9440
    'attr-defined'
]

[[tool.mypy.overrides]]
module = ['ghapi.all', 'matplotlib', 'matplotlib.pyplot',
'pymorphy2', 'pymorphy2.tagset', 'pymystem3']
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ['seminars.*', ]
disable_error_code  = [
    'empty-body',
    'call-overload',
    'operator'
]
